services:
  nginx:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - fluxqa

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - /Users/josh/Development/packages:/Users/josh/Development/packages
    networks:
      - fluxqa

networks:
  fluxqa:
    driver: bridge
